package br.com.visao;

import br.com.controle.CalculadoraFilho;
import javax.swing.JButton;

/**
 *
 * @author ADMIN
 */
public class CalculadoraTela extends javax.swing.JFrame {
    CalculadoraFilho obj = new CalculadoraFilho();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraTela.class.getName());

    /**
     * Creates new form CalculadoraTela
     */
    public CalculadoraTela() {
        initComponents();
        
        javax.swing.ButtonGroup grupo = new javax.swing.ButtonGroup();
        grupo.add(jRvalor1);
        grupo.add(jRvalor2);
        
        // Começam invisíveis
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();
        jBsoma = new javax.swing.JButton();
        jBsubtracao = new javax.swing.JButton();
        jBmultiplicacao = new javax.swing.JButton();
        jBdivisao = new javax.swing.JButton();
        jBsomatoria = new javax.swing.JButton();
        jBraiz = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();
        jRvalor1 = new javax.swing.JRadioButton();
        jRvalor2 = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insira o Valor 1:");

        jLabel2.setText("Insira o Valor 2:");

        jBsoma.setText("+");
        jBsoma.addActionListener(this::jBsomaActionPerformed);

        jBsubtracao.setText("-");
        jBsubtracao.addActionListener(this::jBsubtracaoActionPerformed);

        jBmultiplicacao.setText("*");
        jBmultiplicacao.addActionListener(this::jBmultiplicacaoActionPerformed);

        jBdivisao.setText("/");
        jBdivisao.addActionListener(this::jBdivisaoActionPerformed);

        jBsomatoria.setText("Σ");
        jBsomatoria.addActionListener(this::jBsomatoriaActionPerformed);

        jBraiz.setText("√");
        jBraiz.addActionListener(this::jBraizActionPerformed);

        jLresultado.setText("Resultado:");

        jRvalor1.setText("Raiz do Valor 1");
        jRvalor1.addActionListener(this::jRvalor1ActionPerformed);

        jRvalor2.setText("Raiz do Valor 2");
        jRvalor2.addActionListener(this::jRvalor2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLresultado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTvalor2)
                                    .addComponent(jTvalor1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBsoma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBsubtracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBmultiplicacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBdivisao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBsomatoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBraiz)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRvalor2)
                            .addComponent(jRvalor1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsoma)
                    .addComponent(jBsubtracao)
                    .addComponent(jBmultiplicacao)
                    .addComponent(jBdivisao)
                    .addComponent(jBsomatoria)
                    .addComponent(jBraiz))
                .addGap(18, 18, 18)
                .addComponent(jLresultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRvalor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRvalor2)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomaActionPerformed
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
        pack();
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());
            jLresultado.setText("Resultado: " + obj.adição(v1, v2));
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBsomaActionPerformed

    private void jBsubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubtracaoActionPerformed
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
        pack();
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());
            jLresultado.setText("Resultado: " + obj.subtração(v1, v2));
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBsubtracaoActionPerformed

    private void jBmultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultiplicacaoActionPerformed
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
        pack();
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());
            jLresultado.setText("Resultado: " + obj.multiplicação(v1, v2));
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBmultiplicacaoActionPerformed

    private void jBdivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdivisaoActionPerformed
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
        pack();
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());
            jLresultado.setText("Resultado: " + obj.divisão(v1, v2));
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBdivisaoActionPerformed

    private void jBsomatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomatoriaActionPerformed
        jRvalor1.setVisible(false);
        jRvalor2.setVisible(false);
        pack();
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());

            obj.somatoria(v1, v2); // sobrecarga com parâmetros
            jLresultado.setText("Resultado: " + obj.somatoria()); // sobrecarga sem parâmetros
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBsomatoriaActionPerformed

    private void jBraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBraizActionPerformed
        // Se os radio buttons ainda não estão visíveis, apenas mostre-os
        if (!jRvalor1.isVisible() && !jRvalor2.isVisible()) {
            jRvalor1.setVisible(true);
            jRvalor2.setVisible(true);
            pack();
            jLresultado.setText("Escolha de qual valor deseja a raiz");
            return;
        }
        
        try {
            double v1 = Double.parseDouble(jTvalor1.getText());
            double v2 = Double.parseDouble(jTvalor2.getText());

            // Define os valores internos usados pelo método raiz
            obj.setValores(v1, v2);

            int escolha;
            if (jRvalor1.isSelected()) {
                escolha = 1;
            } else if (jRvalor2.isSelected()) {
                escolha = 2;
            } else {
                jLresultado.setText("Selecione Valor 1 ou Valor 2 para a raiz.");
                return;
            }

            // Chamada ao método sobrescrito em CalculadoraFilho
            jLresultado.setText("Resultado: " + obj.raiz(escolha));
        } catch (NumberFormatException e) {
            jLresultado.setText("Digite apenas números.");
        }
    }//GEN-LAST:event_jBraizActionPerformed

    private void jRvalor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRvalor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRvalor2ActionPerformed

    private void jRvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRvalor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRvalor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdivisao;
    private javax.swing.JButton jBmultiplicacao;
    private javax.swing.JButton jBraiz;
    private javax.swing.JButton jBsoma;
    private javax.swing.JButton jBsomatoria;
    private javax.swing.JButton jBsubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JRadioButton jRvalor1;
    private javax.swing.JRadioButton jRvalor2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
